name = "efg-new-website"
main = "dist/worker.js"
compatibility_date = "2025-05-07"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build && npx @cloudflare/next-on-pages --outdir dist"

[[rules]]
type = "Text"
globs = ["**/*.{html,css,js,json,png,jpg,jpeg,gif,svg,woff,woff2,ttf,eot}"]
fallthrough = true